on:
  issues:
    types: [closed]
jobs:
  build:
    permissions: write-all
    name: closes Jira issue on Github issue Closure
    runs-on: ubuntu-latest
    steps:
    - name: Login
      uses: atlassian/gajira-login@master
      env:
        JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
        JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    - name: get all label names
      run: |
        for label in ${{ github.event.issue.labels }}
          echo "$label.name"
    - name: Find in labels
      id: find
      uses: atlassian/gajira-find-issue-key@v3
      with:
        array: ${{ github.event.issue.labels }}
    - name: Transition issue
      uses: atlassian/gajira-transition@v3
      with:
        issue: ${{ steps.find.outputs.issue }}
        transition: "closed"
